config/routes.rb
Rails.application.routes.draw do
  resources :bank_transactions, only: [:create, :new]
  get "/bank_account", to: "bank_accounts#show"
  devise_for :users

  root "bank_accounts#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  has_many :bank_transactions

  validates :account_number, uniqueness: true

  before_save :generate_account_number, if: Proc.new { account_number.nil? }  

  def transfer(destination_account_number, amount)
    ActiveRecord::Base.transaction do
      destination = BankAccount.find_by(account_number: destination_account_number)

      if validate_destination(destination) && validate_account_balance(amount)
        self.bank_transactions.debit.create(amount: amount)
        destination.bank_transactions.credit.create(amount: amount)
      end 
    end
  end

  private 

  def generate_account_number
    number_generator = -> { Array.new(12) { (0..9).to_a.sample }.join }
    generated_account_number = number_generator.call

    while BankAccount.where(account_number: generated_account_number).first do
      generated_account_number = number_generator.call
    end

    self.account_number = generated_account_number
  end

  def validate_account_balance(amount)
    return true if balance >= amount
    self.errors.add(:balance, "not enough")
    return false
  end

  def validate_destination(destination)
    return true if destination 
    self.errors.add(:base, "Target account not found") 
    return false
  end
end

app/models/bank_transaction.rb
class BankTransaction < ApplicationRecord
  belongs_to :bank_account

  enum transaction_type: { debit: 0, credit: 1 }

  before_save :update_account_balance
  before_validation :check_for_minimum_balance

  def credit_amount
    return nil if debit?
    amount
  end

  def debit_amount
    return nil if credit?
    amount
  end

  private

  def update_account_balance
    if debit?
      self.running_balance = bank_account.balance - amount
      bank_account.update(balance: running_balance)
    elsif credit?
      self.running_balance = bank_account.balance + amount
      bank_account.update(balance: running_balance)
    else
      self.errors.add(:transaction_type, "Unknown transaction type")
      raise ActiveRecord::RecordInvalid.new(self)
    end
  end

  def check_for_minimum_balance
    if debit?
      if amount > bank_account.balance 
        self.errors.add(:amount, "Not enough money in bank account")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_one :bank_account
  has_many :bank_transactions, through: :bank_account

  validates :name, presence: true

  after_create :create_bank_account, if: Proc.new { bank_account.nil? }

  def add_funds(amount)
    self.bank_account.update(balance: bank_account.balance + amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized 

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def set_bank_account
    @bank_account = current_user.bank_account
    authorize @bank_account, :show?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: %i[ show ]

  # GET /bank_accounts/1 or /bank_accounts/1.json
  def show
    @transactions = @bank_account.bank_transactions.order(created_at: :desc)
  end
end

app/controllers/bank_transactions_controller.rb
class BankTransactionsController < ApplicationController
  before_action :set_bank_transaction, only: %i[ show ]
  before_action :set_bank_account

  # GET /bank_transactions/1 or /bank_transactions/1.json
  def show
  end

  # GET /bank_transactions/new
  def new
    @bank_transaction = BankTransaction.new
  end

  # POST /bank_transactions or /bank_transactions.json
  def create
    @bank_transaction = BankTransaction.new
    target_account = bank_transaction_params[:bank_account][:account_number]
    amount = bank_transaction_params[:amount].to_f

    respond_to do |format|
      if @bank_account.transfer(target_account, amount)
        format.html { redirect_to bank_account_path, notice: "Bank transaction was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_bank_transaction
    @bank_transaction = BankTransaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bank_transaction_params
    params.require(:bank_transaction).permit(:amount, bank_account: [ :account_number ] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/bank_transactions_helper.rb
module BankTransactionsHelper
end

app/views/bank_accounts/_bank_transactions.html.erb
<% if transactions.size > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Debit</th>
        <th>Credit</th>
        <th>Running Balance</th>
      </tr>
    </thead>
    <tbody>
      <% transactions.each do |transaction| %>
        <tr>
          <th><%= transaction.created_at %></th>
          <th><%= number_to_currency transaction.debit_amount %></th>
          <th><%= number_to_currency transaction.credit_amount %></th>
          <th><%= number_to_currency transaction.running_balance %></th>
        </tr>
      <% end %>
    </tbody> 
  </table>
<% else %>
  <span>This account has no transactions.</span>
<% end %>

app/views/bank_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"> Welcome <%= current_user.name %>, </h5>
    <p>
      Your account number is: <strong><%= @bank_account.account_number %></strong><br/>
      Your current balance is: <strong><%= number_to_currency @bank_account.balance %></strong>
    </p>
    <%= link_to "Create New Transaction", new_bank_transaction_path, class: "card-link btn btn-primary" %>
  </div>
</div>

<div>
  Here are your latest transactions:

  <%= render partial: "bank_transactions", locals: { transactions: @transactions } %>
</div>

<footer>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
</footer>

app/views/bank_transactions/_form.html.erb
<%= form_with(model: bank_transaction) do |form| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_transaction from being saved:</h2>

      <ul>
        <% @bank_account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label "Destination Account Number (12-digits)", class: "form-label" %>
    <%= form.text_field "bank_account[account_number]", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", min: 1, step: "any" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', bank_account_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/bank_transactions/edit.html.erb
<h1>Editing Bank Transaction</h1>

<%= render 'form', bank_transaction: @bank_transaction %>

<%= link_to 'Show', @bank_transaction %> |
<%= link_to 'Back', bank_transactions_path %>

app/views/bank_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bank Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Bank account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_transactions.each do |bank_transaction| %>
      <tr>
        <td><%= bank_transaction.bank_account_id %></td>
        <td><%= link_to 'Show', bank_transaction %></td>
        <td><%= link_to 'Edit', edit_bank_transaction_path(bank_transaction) %></td>
        <td><%= link_to 'Destroy', bank_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank Transaction', new_bank_transaction_path %>

app/views/bank_transactions/new.html.erb
<h1>Bank Transfer</h1>

<%= render 'form', bank_transaction: @bank_transaction %>

app/views/bank_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank account:</strong>
  <%= @bank_transaction.bank_account_id %>
</p>

<%= link_to 'Back', bank_account_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>